# Generated by Django 4.2.7 on 2023-12-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timesheet", "0004_alter_timesheet_hours_worked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheet",
            name="week_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
