# Generated by Django 4.2.7 on 2023-12-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timesheet", "0005_alter_timesheet_week_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timesheet",
            name="project",
        ),
        migrations.AddField(
            model_name="timesheet",
            name="projects",
            field=models.ManyToManyField(to="timesheet.project"),
        ),
    ]
